In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    accuracy_score,
    classification_report
)
from sklearn.base import clone
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier,
    StackingClassifier,
)

In [2]:
df = pd.read_csv("../data/raw/churn.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df.shape

(10000, 14)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [5]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [6]:
columns_to_drop = ["RowNumber", "CustomerId", "Surname"]
df.drop(columns_to_drop, axis=1, inplace=True)

In [7]:
df.shape

(10000, 11)

In [8]:
X = df.drop(['Exited'], axis=1)
y = df['Exited']
print(X.shape, y.shape)

(10000, 10) (10000,)

In [9]:
num_vars = X.select_dtypes(include=[np.number]).columns.tolist()
cat_var = X.select_dtypes(include=['object', 'category']).columns.tolist()

/tmp/ipykernel_5978/4003200763.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_var = X.select_dtypes(include=['object', 'category']).columns.tolist()

In [10]:
num_vars

['CreditScore',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary']

In [11]:
cat_var

['Geography', 'Gender']

In [12]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [13]:
for col in cat_var:
    print(col, df[col].unique())

Geography <StringArray>
['France', 'Spain', 'Germany']
Length: 3, dtype: str
Gender <StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [14]:
ohe = OneHotEncoder(drop='first', sparse_output=False)
ohe

OneHotEncoder(drop='first', sparse_output=False)

In [15]:
y.value_counts(normalize=True) * 100

Exited
0    79.63
1    20.37
Name: proportion, dtype: float64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [17]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8000, 10), (2000, 10), (8000,), (2000,))

In [18]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_vars),
        ("cat", OneHotEncoder(
            drop="first",
            sparse_output=False
        ), cat_var)
    ]
)
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['CreditScore', 'Age', 'Tenure', 'Balance',
                                  'NumOfProducts', 'HasCrCard',
                                  'IsActiveMember', 'EstimatedSalary']),
                                ('cat',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['Geography', 'Gender'])])

In [19]:
X_train_scaled = preprocessor.fit_transform(X_train)
X_test_scaled = preprocessor.transform(X_test)

In [20]:
X_test_scaled

array([[-0.68073539, -0.27993196,  0.68472287, ...,  0.        ,
         0.        ,  1.        ],
       [-1.30191518, -0.5649346 , -0.35097064, ...,  1.        ,
         0.        ,  1.        ],
       [-0.97061929,  0.10007155, -0.35097064, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-1.39509214,  0.7650777 ,  1.3751852 , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.39597623,  0.00507067,  0.68472287, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.02750901, -0.5649346 , -1.04143297, ...,  0.        ,
         0.        ,  1.        ]], shape=(2000, 11))

In [21]:
X_test_scaled

array([[-0.68073539, -0.27993196,  0.68472287, ...,  0.        ,
         0.        ,  1.        ],
       [-1.30191518, -0.5649346 , -0.35097064, ...,  1.        ,
         0.        ,  1.        ],
       [-0.97061929,  0.10007155, -0.35097064, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-1.39509214,  0.7650777 ,  1.3751852 , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.39597623,  0.00507067,  0.68472287, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.02750901, -0.5649346 , -1.04143297, ...,  0.        ,
         0.        ,  1.        ]], shape=(2000, 11))

In [22]:
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42)
}

models_pipelines = {}
for name, model in models.items():
    pipe = Pipeline([
        ('preprocessor', preprocessor),
        ('model', model)
    ])

    pipe.fit(X_train, y_train)
    models_pipelines[name] = pipe
    y_pred = pipe.predict(X_test)
    y_prob = pipe.predict_proba(X_test)[:, 1]

    print(f"\n{name}")
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall:", recall_score(y_test, y_pred))
    print("F1-score:", f1_score(y_test, y_pred))
    print("ROC-AUC:", roc_auc_score(y_test, y_prob))

Logistic Regression
Precision: 0.5891472868217055
Recall: 0.18673218673218672
F1-score: 0.2835820895522388
ROC-AUC: 0.77475626628169

Decision Tree
Precision: 0.46846846846846846
Recall: 0.5110565110565111
F1-score: 0.4888366627497062
ROC-AUC: 0.6814541814541815

Random Forest
Precision: 0.7824267782426778
Recall: 0.4594594594594595
F1-score: 0.5789473684210527
ROC-AUC: 0.8522181657774878

In [23]:
models_pipelines

{'Logistic Regression': Pipeline(steps=[('preprocessor',
                  ColumnTransformer(transformers=[('num', StandardScaler(),
                                                   ['CreditScore', 'Age',
                                                    'Tenure', 'Balance',
                                                    'NumOfProducts', 'HasCrCard',
                                                    'IsActiveMember',
                                                    'EstimatedSalary']),
                                                  ('cat',
                                                   OneHotEncoder(drop='first',
                                                                 sparse_output=False),
                                                   ['Geography', 'Gender'])])),
                 ('model', LogisticRegression(max_iter=1000))]),
 'Decision Tree': Pipeline(steps=[('preprocessor',
                  ColumnTransformer(transformers=[('num', StandardScaler(),
                                                   ['CreditScore', 'Age',
                                                    'Tenure', 'Balance',
                                                    'NumOfProducts', 'HasCrCard',
                                                    'IsActiveMember',
                                                    'EstimatedSalary']),
                                                  ('cat',
                                                   OneHotEncoder(drop='first',
                                                                 sparse_output=False),
                                                   ['Geography', 'Gender'])])),
                 ('model', DecisionTreeClassifier(random_state=42))]),
 'Random Forest': Pipeline(steps=[('preprocessor',
                  ColumnTransformer(transformers=[('num', StandardScaler(),
                                                   ['CreditScore', 'Age',
                                                    'Tenure', 'Balance',
                                                    'NumOfProducts', 'HasCrCard',
                                                    'IsActiveMember',
                                                    'EstimatedSalary']),
                                                  ('cat',
                                                   OneHotEncoder(drop='first',
                                                                 sparse_output=False),
                                                   ['Geography', 'Gender'])])),
                 ('model', RandomForestClassifier(random_state=42))])}

In [24]:
base_models = [
    ("rf", RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        min_samples_split=10,
        min_samples_leaf=5,
        class_weight="balanced_subsample",
        random_state=42,
        n_jobs=-1,
    )),
    ("gb", GradientBoostingClassifier(
        n_estimators=150,
        learning_rate=0.05,
        random_state=42,
    )),
    ("xgb", XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1,
    )),
    ("lgbm", LGBMClassifier(
        n_estimators=200,
        learning_rate=0.05,
        verbosity=-1,
        random_state=42,
        n_jobs=-1,
    )),
]

In [25]:
estimators = [
    (name, Pipeline([
        ("preprocessor", clone(preprocessor)),
        ("model", model),
    ]))
    for name, model in base_models
]

stacking_model = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
    ),
    cv=5,
    stack_method="predict_proba",
    n_jobs=-1,
)


stacking_model.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('rf',
                                Pipeline(steps=[('preprocessor',
                                                 ColumnTransformer(transformers=[('num',
                                                                                  StandardScaler(),
                                                                                  ['CreditScore',
                                                                                   'Age',
                                                                                   'Tenure',
                                                                                   'Balance',
                                                                                   'NumOfProducts',
                                                                                   'HasCrCard',
                                                                                   'IsActiveMember',
                                                                                   'EstimatedSalary']),
                                                                                 ('cat',
                                                                                  OneHotEncoder(drop='first',
                                                                                                sparse_output=False),
                                                                                  ['Geography',
                                                                                   'Gender'])])),
                                                ('model',
                                                 RandomForestClassifier(c...
                                                                                   'NumOfProducts',
                                                                                   'HasCrCard',
                                                                                   'IsActiveMember',
                                                                                   'EstimatedSalary']),
                                                                                 ('cat',
                                                                                  OneHotEncoder(drop='first',
                                                                                                sparse_output=False),
                                                                                  ['Geography',
                                                                                   'Gender'])])),
                                                ('model',
                                                 LGBMClassifier(learning_rate=0.05,
                                                                n_estimators=200,
                                                                n_jobs=-1,
                                                                random_state=42,
                                                                verbosity=-1))]))],
                   final_estimator=LogisticRegression(class_weight='balanced',
                                                      max_iter=1000),
                   n_jobs=-1, stack_method='predict_proba')

In [26]:
y_prob_stack = stacking_model.predict_proba(X_test)[:, 1]
y_pred_stack = (y_prob_stack >= 0.35).astype(int)

# Calculate metrics
print("Stacking Classifier (Threshold = 0.35)")
print("-" * 40)
print("Accuracy:", accuracy_score(y_test, y_pred_stack))
print("Precision:", precision_score(y_test, y_pred_stack, zero_division=0))
print("Recall:", recall_score(y_test, y_pred_stack, zero_division=0))
print("F1-score:", f1_score(y_test, y_pred_stack, zero_division=0))
print("ROC-AUC:", roc_auc_score(y_test, y_prob_stack))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_stack, zero_division=0))

Stacking Classifier (Threshold = 0.35)
----------------------------------------
Accuracy: 0.7365
Precision: 0.425
Recall: 0.8353808353808354
F1-score: 0.5633802816901409
ROC-AUC: 0.8705377179953451

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.71      0.81      1593
           1       0.42      0.84      0.56       407

    accuracy                           0.74      2000
   macro avg       0.68      0.77      0.69      2000
weighted avg       0.84      0.74      0.76      2000